### PR TITLE
Fix Null Deref crash

### LINKED ISSUE #520: NULL Deref crash in `ReadFileAsyncHook`
`pPath` [here](https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDLL/core/filesystem/rpakfilesystem.cpp#L259) is the culprit. This seems to be very rare

Stack trace:
```
Northstar.dll + 0xa3c23
materialsystem_dx11.dll + 0x9955b
materialsystem_dx11.dll + 0x99396
materialsystem_dx11.dll + 0x8c12
materialsystem_dx11.dll + 0x8808f
tier0.dll + 0x1ba3b
KERNEL32.DLL + 0x17614
ntdll.dll + 0x526b1
```

Ill try to figure out why this is happening, but either way will PR a fix

### PR DESCRIPTION
**Pull request by Alystrasz**
Recreation of https://github.com/R2Northstar/NorthstarLauncher/pull/521 since it got reverted.
Original description:

> Fixes a NULL dereference crash in `ReadFileAsync`
> 
> This seems to be very rare, there's currently an open [ticket](https://discord.com/channels/920776187884732556/1134199951971332096) where this occurs. This version hasnt been tested yet.
> 
> I also promised to ping `@shmordan_08` when this gets released
> 
> Closes #520

### CODE REVIEW

**Comment by Alystrasz** [comment]
Note that this won't build, `ReadFileAsync` function being removed in 160f503.

File: primedev/core/filesystem/rpakfilesystem.cpp [hunk 1]
```diff
@@ -484,6 +484,14 @@ HOOK(OpenFileHook, o_pOpenFile,
 void*, __fastcall, (const char* pPath, void* pCallback))
 // clang-format on
 {
+	// NOTE [Fifty]: For some reason some users are getting pPath as null when
+	//               loading a server, ReadFileAsync uses CreateFileA and checks
+	//               its return value so this is completely safe
+	if (pPath == NULL)
+	{
+		return ReadFileAsync(pPath, pCallback);
```
Comment (ASpoonPlaysGames) [inline primedev/core/filesystem/rpakfilesystem.cpp:492]:
```suggestion
		return o_pOpenFile(pPath, pCallback);
```

File: primedev/core/filesystem/rpakfilesystem.cpp [hunk 2]
```diff
@@ -484,6 +484,14 @@ HOOK(OpenFileHook, o_pOpenFile,
 void*, __fastcall, (const char* pPath, void* pCallback))
 // clang-format on
 {
+	// NOTE [Fifty]: For some reason some users are getting pPath as null when
+	//               loading a server, ReadFileAsync uses CreateFileA and checks
```
Comment (ASpoonPlaysGames) [inline primedev/core/filesystem/rpakfilesystem.cpp:488]:
```suggestion
	//               loading a server, o_pOpenFile uses CreateFileA and checks
```

**Review by ASpoonPlaysGames — COMMENTED** [review]
I *think* this is just a case of a renamed function. This might do the trick.

File: primedev/core/filesystem/rpakfilesystem.cpp [hunk 3]
```diff
@@ -484,6 +484,14 @@ HOOK(OpenFileHook, o_pOpenFile,
...
 // clang-format on
 {
+	// NOTE [Fifty]: For some reason some users are getting pPath as null when
+	//               loading a server, o_pOpenFile uses CreateFileA and checks
+	//               its return value so this is completely safe
+	if (pPath == NULL)
+	{
+		return o_pOpenFile(pPath, pCallback);
+	}
+
```
Comment (ASpoonPlaysGames) [inline primedev/core/filesystem/rpakfilesystem.cpp:494]:
```suggestion

```

Comment (ASpoonPlaysGames) [reply primedev/core/filesystem/rpakfilesystem.cpp]: Well, github suggestion thing just nuked the line instead of removing the whitespace, whatever

File: primedev/core/filesystem/rpakfilesystem.cpp [hunk 4]
```diff
@@ -484,6 +484,13 @@ HOOK(OpenFileHook, o_pOpenFile,
 void*, __fastcall, (const char* pPath, void* pCallback))
 // clang-format on
 {
+	// NOTE [Fifty]: For some reason some users are getting pPath as null when
+	//               loading a server, o_pOpenFile uses CreateFileA and checks
+	//               its return value so this is completely safe
+	if (pPath == NULL)
+	{
+		return o_pOpenFile(pPath, pCallback);
+	}
```
Comment (ASpoonPlaysGames) [inline primedev/core/filesystem/rpakfilesystem.cpp:493]:
```suggestion
	}

```

**Comment by ASpoonPlaysGames** [comment]
Right I think this is fine now, should compile and stuff

**Comment by Alystrasz** [comment]
Thanks @ASpoonPlaysGames for reviewing this!
So this function was just renamed, we should be good to go! Right? Right?
