### PR TITLE
Fix proton detection output

### LINKED ISSUE #533: Proton detection prints incorrect basename
Detecting while working on Proton support

Newer proton versions also list the steam linux runtime in their compat tool paths.

Here is an example of the value it may be set to
```
STEAM_COMPAT_TOOL_PATHS=/home/user/.local/share/Steam/compatibilitytools.d/NorthstarProton:/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper
```

### PR DESCRIPTION
**Pull request by Jan200101**
fixes #533 

image

Also adds some comments to explain what is going on and puts values into variables instead of using the return value directly.
Yes I used auto, sue me.

### CODE REVIEW

File: NorthstarDLL/logging/logging.cpp [hunk 1]
```diff
@@ -261,12 +261,18 @@ void StartupLog()
 		spdlog::info("Operating System: {} (Wine)", sysname);
 		spdlog::info("Wine build: {}", wine_get_build_id());
 
+		// STEAM_COMPAT_TOOL_PATHS is a colon separated lists of all compat tool paths used
+		// The first one tends to be the Proton path itself
```
Comment (ASpoonPlaysGames) [inline NorthstarDLL/logging/logging.cpp:265]: Tends to be? Doesn't this mean that this PR only fixes the cases where it was broken, but breaks cases where it wasn't?

Could we just look for the `NorthstarProton` + `:`/`0x00` substring to find it more consistently?

File: NorthstarDLL/logging/logging.cpp [hunk 2]
```diff
@@ -261,12 +261,18 @@ void StartupLog()
...
+		// We extract the basename out of it to get the name used
 		char* compatToolPtr = std::getenv("STEAM_COMPAT_TOOL_PATHS");
 		if (compatToolPtr)
 		{
 			std::string compatToolPath(compatToolPtr);
 
-			spdlog::info("Proton build: {}", compatToolPath.substr(compatToolPath.rfind("/") + 1));
+			auto protonBasenameEnd = compatToolPath.find(":");
```
Comment (ASpoonPlaysGames) [inline NorthstarDLL/logging/logging.cpp:272]: If there is only one compat tool, wont this be `std::string::npos`? This wouldn't break the later code would it?

File: NorthstarDLL/logging/logging.cpp (hunk 1 above)
Comment (Jan200101) [reply NorthstarDLL/logging/logging.cpp:265]: > Tends to be? Doesn't this mean that this PR only fixes the cases where it was broken, but breaks cases where it wasn't?

Entries to the list are appended to the end, so when Proton steam puts it as the first entry.
But this isn't set in stone and may change in the future.

> Could we just look for the NorthstarProton + :/0x00 substring to find it more consistently?

NorthstarProton is not a requirement, only a suggestion.
GE-Proton works just as well (arguably even better).

a colon is only added between multiple entries.

File: NorthstarDLL/logging/logging.cpp (hunk 2 above)
Comment (Jan200101) [reply NorthstarDLL/logging/logging.cpp:272]: yeah, it would.

Comment (Jan200101) [reply NorthstarDLL/logging/logging.cpp:272]: Should be fixed by c92531ff6a1ade76546589fae16d50e5cc7b630f

File: NorthstarDLL/logging/logging.cpp (hunk 1 above)
Comment (ASpoonPlaysGames) [reply NorthstarDLL/logging/logging.cpp:265]: > NorthstarProton is not a requirement, only a suggestion.
> GE-Proton works just as well (arguably even better).

Fair enough. I guess we can't really guarantee 100% accuracy here then

**Review by ASpoonPlaysGames — APPROVED** [review]
Code looks good :)

**Comment by Jan200101** [comment]
Maybe the log entry should say "Compatibility tool" instead of "Proton version"

**Comment by ASpoonPlaysGames** [comment]
> Maybe the log entry should say "Compatibility tool" instead of "Proton version"

If so, is there a downside to just logging the entirety of `STEAM_COMPAT_TOOL_PATHS`?

**Comment by Jan200101** [comment]
> If so, is there a downside to just logging the entirety of `STEAM_COMPAT_TOOL_PATHS`?
no, but it could become a bit cluttered since the main compat tool can pull in a variety of other things.

File: NorthstarDLL/logging/logging.cpp [hunk 3]
```diff
@@ -261,12 +261,22 @@ void StartupLog()
 		spdlog::info("Operating System: {} (Wine)", sysname);
 		spdlog::info("Wine build: {}", wine_get_build_id());
 
+		// STEAM_COMPAT_TOOL_PATHS is a colon separated lists of all compat tool paths used
+		// The first one tends to be the Proton path itself
+		// We extract the basename out of it to get the name used
 		char* compatToolPtr = std::getenv("STEAM_COMPAT_TOOL_PATHS");
 		if (compatToolPtr)
 		{
 			std::string compatToolPath(compatToolPtr);
```
Comment (p0358) [inline NorthstarDLL/logging/logging.cpp:270]: You should change `std::string` to `std::string_view`, as there's no point allocating a new string, whereas string_view was designed exactly for this. Remember to change it for `npos` too.

Comment (p0358) [reply NorthstarDLL/logging/logging.cpp:270]: Btw spdlog's formatter would cast std::string to basic_string_view anyways

Comment (Jan200101) [reply NorthstarDLL/logging/logging.cpp:270]: Yeah, in theory there should be nothing that could mess with the env pointers so string_view should be fine.

**Review by H0L0theBard — APPROVED** [review]
Code looks good and works as intended :+1:

image

**Comment by GeckoEidechse** [comment]
Merging based on reviews.
